import { APP_CONFIG, STORAGE_KEYS, CURRENCY_FORMAT, FEATURES, MESSAGES, UI_CONFIG } from '@/config';

// App config
export const DEFAULT_BASE_CURRENCY = APP_CONFIG.DEFAULT_BASE_CURRENCY;
export const DEFAULT_TARGET_CURRENCIES = APP_CONFIG.DEFAULT_TARGET_CURRENCIES;

export const DATE_RANGE = {
  DAYS_TO_SHOW: APP_CONFIG.DAYS_TO_SHOW,
  MAX_DAYS_BACK: APP_CONFIG.MAX_DAYS_BACK,
};

// Storage keys
export { STORAGE_KEYS };

// Messages
export const ERROR_MESSAGES = MESSAGES.ERROR;
export const SUCCESS_MESSAGES = MESSAGES.SUCCESS;

// UI config
export const TABLE_CONFIG = UI_CONFIG.TABLE;
export const CHART_CONFIG = UI_CONFIG.CHART;

// Currency format
export const CURRENCY_FORMAT_OPTIONS = CURRENCY_FORMAT;

// Feature flags
export const FEATURE_FLAGS = FEATURES;
